config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'

  get  'about'       => 'welcome#about'
  get  'contact'     => 'welcome#contact'
  get  'help'        => 'welcome#help'
  resources :charges
  get  'downgrade'   => 'charges#downgrade'
  post 'downgrade'   => 'charges#downgrade_posts'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :collaborators
  end
  authenticated :user do
   root 'posts#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :user_collaborators, through: :collaborators, source: :user
  default_scope { order(updated_at: :desc) }
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
before_action :authenticate_user!

  def index
  end

  def show
    @post=Post.find(params[:id])
    authorize @post
    @users=User.where.not( id: current_user.id, role: 'admin' ).paginate(page: params[:page], per_page: 10)
  end

  def new
  end

  def create
    @collaborator = Collaborator.new
    @collaborator.user_id=params[:user_id]
    @collaborator.post_id=params[:post_id]
    if @collaborator.save # Calling database save/insert command
      flash[:success] = 'User was added.'
      redirect_to action: "show", id: @collaborator.post_id
    else
      flash.now[:danger] = 'There was an error adding the user. Please try again.'
      redirect_to action: "show", id: @collaborator.post_id # render the new view again
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @post=Post.find(params[:post_id])
    authorize @post
    @collaborator = Collaborator.find(params[:id])
    @user=User.find( @collaborator.user_id )

    if @collaborator.destroy
      flash[:success] = "\"#{@user.email}\" was removed successfully."
      redirect_to action: "show", id: @collaborator.post_id
    else
      flash.now[:danger] = 'There was an error removing the user.'
      redirect_to action: "show", id: @collaborator.post_id
    end
  end


end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/views/collaborators/create.html.erb
<h1> you can find me in app/views/collaborators/create.html.erb </h1>

app/views/collaborators/delete.html.erb
<h1>Collaborators#delete</h1>
<p>Find me in app/views/collaborators/delete.html.erb</p>

app/views/collaborators/edit.html.erb
<h1> Add / Remove Collaborators </h1>
<h2>Title: <%= @post.title %></h2>
<div>

  <div class="row">
    <div class="col-sm-3 center">
      <h3>Name</h3>
    </div>
    <div class="col-sm-3 center">
    </div>
    <div class="col-sm-1 center">
      <h3>Access</h3>
    </div>
  </div>

  <%= form_for @post, url: post_collaborator_path do |f| %>
    <%= hidden_field_tag "@post.user_collaborator_ids[user_ids][]", nil %>
    <% @users.each do |user| %>
      <%= check_box_tag "@post.user_collaborator_ids[user_ids][]", user.id, @post.user_collaborator_ids.include?(user.id) %>
      <%= user.name %> (<%= user.email %>)<br>
    <% end %>
    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>

</div>

app/views/collaborators/index.html.erb
<h1>Collaborators#index</h1>
<p>Find me in app/views/collaborators/index.html.erb</p>

app/views/collaborators/new.html.erb
<h1>Collaborators#new</h1>
<p>Find me in app/views/collaborators/new.html.erb</p>

app/views/collaborators/show.html.erb
<h1> Add / Remove Collaborators </h1>
<h2><strong>Title: <%= @post.title %></strong></h2>
<%= will_paginate @users %>
<div class="table table-responsive">
    <table class="table">
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td>
            <% if @post.user_collaborators.include?(user) %>
              <% collaborator = @post.collaborators.where(user_id: user.id).first %>
              <%= link_to "Remove", [@post, collaborator], method: :delete, class: "btn btn-danger" %>
            <% else %>
              <%= link_to "Add", post_collaborators_path(@post, user_id: user.id), method: :post, class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </table>
  </div>