config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'

  get  'about'       => 'welcome#about'
  get  'contact'     => 'welcome#contact'
  get  'help'        => 'welcome#help'
  resources :charges
  get  'downgrade'   => 'charges#downgrade'
  post 'downgrade'   => 'charges#downgrade_posts'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :collaborators
  end
  authenticated :user do
   root 'posts#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :user_collaborators, through: :collaborators, source: :user
  default_scope { order(updated_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!

  # Show only public, own, and collaborated wiki
  def index
    @posts = policy_scope(Post).paginate(page: params[:page], per_page: 15)
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def collaborate
    @post = Post.find(params[:id])
    authorize @post
  end

  def checkbox
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.private = params[:post][:private] || @post.private

    if @post.save # Calling database save/insert command
      flash[:success] = 'Post was saved.'
      redirect_to @post # Redirecting to @post will direct the user to the posts show view.
    else
      flash.now[:danger] = 'There was an error saving the post. Please try again.'
      render :new # render the new view again
    end
  end

  def create
    @post = Post.new
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]
    @post.private = params[:post][:private]
    @post.user = current_user

    if @post.save # Calling database save/insert command
      flash[:success] = 'Post was saved.'
      redirect_to @post # Redirecting to @post will direct the user to the posts show view.
    else
      flash.now[:danger] = 'There was an error saving the post. Please try again.'
      render :new # render the new view again
    end
  end

  def destroy
    @post = Post.find(params[:id])
    authorize @post

    if @post.destroy
      flash[:success] = "\"#{@post.title}\" was deleted successfully."
      redirect_to posts_path
    else
      flash.now[:danger] = 'There was an error deleting the post.'
      render :show
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1> Edit Post </h1>
    <%= form_for @post do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body"%>
      </div>
      <!-- Only owner or admin can change post privacy -->
      <% if policy(@post).checkbox? -%>
        <div class="field">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private
          <% end %>
        </div>
      <% end %>
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<h1>All Posts</h1>

<% if policy(current_user).premium? -%>
 <div class="pull-right">
   <%= link_to "New Post", new_post_path, class: 'btn btn-success' %><br>
 </div>
<% end %>

<ul>
 <% @posts.each do |post| %>
    <% if (post.user_id == current_user.id) %>
      <li><%= link_to post.title, post, class:'mine' %></li>
    <% else %>
      <li><%= link_to post.title, post %></li>
    <% end %> 
 <% end %>
</ul>
 <%= will_paginate %>

app/views/posts/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1> New Post </h1>
    <%= form_for @post do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      </div>

      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body"%>
      </div>

      <% if current_user.admin? || current_user.premium?  -%>
        <div class="field">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private
          <% end %>
        </div>
      <% end %>

      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>
  <p><strong>Submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %> (<%= @post.user.email %>)</strong><p>
  <p>Updated <%=time_ago_in_words(@post.updated_at) %> ago</p><br>
</h2>

<% if policy(@post).update? -%>
    <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-success' %>
<% end %>
<% if policy(@post).destroy? -%>
    <%= link_to "Delete", @post, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
<% end -%>
<% if policy(@post).collaborate? -%>
    <%= link_to "Collaboration", post_collaborator_path(@post), class: 'btn btn-primary' %>
<% end -%>
<p><br></p>
<div class="row">
  <div class="col-md-12">
    <%= markdown(@post.body) %>
  </div>
</div>