config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'

  get  'about'       => 'welcome#about'
  get  'contact'     => 'welcome#contact'
  get  'help'        => 'welcome#help'
  resources :charges
  get  'downgrade'   => 'charges#downgrade'
  post 'downgrade'   => 'charges#downgrade_posts'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :collaborators
  end
  authenticated :user do
   root 'posts#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def index
  end

  def show
  end

  def downgrade
    @private_posts = current_user.posts.where(private: true) # User private wiki list
  end

  def downgrade_posts
    #Change User wikis from private to public and user to standard
    if ( current_user.posts.update_all( private: false ) && current_user.standard! )
      flash[:success] = 'Your account has been downgraded to Standard'
      redirect_to root_path
    else
      flash.now[:danger] = 'There was an error downgrading your account. Please try again.'
      render :edit # render the new view again
    end
  end

  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Wikiikki Premium Membership - #{current_user.name}",
      #amount: Amount.default
      amount: 10_00
    }
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      #amount: Amount.default,
      amount: 10_00,
      description: "Wikiikki Premium Membership - #{current_user.email}",
      currency: 'usd'
    )

    # Change User role to premium
    #User.find(current_user.id).update_attribute( :role, 'premium')
    #flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    #redirect_to root_path # or wherever

    if charge.paid  # https://stripe.com/docs/api/ruby#charges
      current_user.premium! # prefer using the enum methods for brevity and clarity
      flash[:success] = "Payment received from #{current_user.email}."
      redirect_to root_path # or wherever
    end
    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
    rescue Stripe::CardError => e
      flash[:danger] = e.message
      redirect_to new_charge_path
  end # create

end #Class

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/delete.html.erb
#

app/views/charges/downgrade.html.erb
<h1> Downgrade Account</h1>
<h2> Warning! The following posts will be converted to Public after you switch back to Standard account.</h2>
<div>
  <% @private_posts.each do |post| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <%= link_to post.title, post %>
        </h4>
      </div>
    </div>
  <% end %>
</div>
<%= button_to "Downgrade", action: "downgrade_posts" %>

app/views/charges/edit.html.erb
#

app/views/charges/index.html.erb
#

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
          data-key="<%= @stripe_btn_data[:key] %>" 
          data-amount="<%= @stripe_btn_data[:amount] %>" 
          data-description="<%= @stripe_btn_data[:description] %>" >
  </script>
<% end %>

app/views/charges/show.html.erb
#