config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'

  get  'about'       => 'welcome#about'
  get  'contact'     => 'welcome#contact'
  get  'help'        => 'welcome#help'
  resources :charges
  get  'downgrade'   => 'charges#downgrade'
  post 'downgrade'   => 'charges#downgrade_posts'
  devise_for :users
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  
  resources :posts do
    resources :collaborators
  end
  authenticated :user do
   root 'posts#index', as: :authenticated_root
  end
  root 'welcome#index'
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Wikiikki App by Minh Nguyen
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Wikiikki", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Posts", posts_path %></li>
          <% if current_user.admin? %>
            <li><%= link_to "Users", users_index_path %></li>  
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", edit_user_registration_path %></li>
              <% if policy(current_user).premium? %>
                <li><%= link_to "Downgrade", downgrade_path %></li>
              <% else %>
                <li><%= link_to "Upgrade", new_charge_path %></li>
              <% end %>
              <li><%= link_to "Cancel Account", admin_destroy_user_path(current_user), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to remove your account?'} %></li>
             <li class="divider"></li>
              <li>
                <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% if user_signed_in? %>
  <div class="center"><strong><%= current_user.name %></strong> (<%= current_user.email %>) </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->
<!-- If IE use the latest rendering engine -->
<meta http-equiv="X-UA-Compatible" content="IE=edge">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocpedia</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %><br>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>

</html>